### ISSUE TITLE
Release automation ~broken

### ISSUE THREAD

**Issue by colindean** [colindean/fillertext#39]
Looks like our shiny new release automation isn't quite working. The release-please action seems to be working but juwelier's `rake release` task needs some info.

https://github.com/colindean/fillertext/runs/4026234565?check_suite_focus=true#step:6:1

I think minimally it needs to have a full `git config user.{name,email}` set but there's also something about the `VERSION` file not being updated: #38 should have contained that update and it didn't...?

@Ashvith thoughts?

**Comment by Ashvith** [comment]
@colindean can you check out the **[migrate_from_juwlier](https://github.com/Ashvith/fillertext/tree/migrate_from_juwlier)** branch in my repo ? The test cases need to be worked on, which I'll fix in my spare time.

**Comment by colindean** [comment]
#41 is done and this is building now. If the release publishes correctly, it's done!

**Comment by Ashvith** [comment]
Looks like the latest version v.0.3.2 is failing, because of a Rubocop offense, which is quite easy to fix. Simply typing in `rubocop --auto-correct` would fix the offense.

**Comment by colindean** [comment]
![It's working!](https://www.reactiongifs.us/wp-content/uploads/2013/07/its_working_star_wars.gif)

Thank you for your help, @Ashvith!

**Comment by colindean** [comment]
https://rubygems.org/gems/fillertext/versions/0.3.4
