### ISSUE TITLE
Add instructions to README for contribution

### ISSUE THREAD

**Issue by Ashvith10** [colindean/fillertext#48]
This can be simply included in the `README.md` file. Here are some starter ideas I have come up with, which could be included.

- [x] **How to start with the project?**: Fork the project and run `bundle install` to install all the required dependencies
- [x] **How to install the gem**: Run `gem install fillertext`
- [x] **How to test the project?**: Simply run `rspec`. To run a specific test, run `rspec spec/<test_you're_interested_in>_spec.rb`
- [x] **How to access code coverage details**: First run `rspec`, then `xdg-open coverage/index.html` (Linux) or `open coverage/index.html` (Mac)

**Comment by colindean** [comment]
I'd welcome a PR that includes these in the README!
